name: First Linux Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Check Google Connectivity
      run: |
        echo "Starting health check..."
        
        # 'curl' is a tool to transfer data. '-I' fetches the headers only.
        # This simulates checking if a server is responsive.
        curl -I https://www.google.com
        
        echo "Health check passed!"